# Generated by Django 4.2.16 on 2025-01-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField(blank=True, max_length=500, null=True)),
                ('emails', models.TextField()),
                ('phone_numbers', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('communication_periodicity', models.CharField(default='2 weeks', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('highlight', models.CharField(default='Green', max_length=10)),
                ('communication_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.communicationmethod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_schedule', to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('LinkedIn Post', 'LinkedIn Post'), ('LinkedIn Message', 'LinkedIn Message'), ('Email', 'Email'), ('Phone Call', 'Phone Call'), ('Other', 'Other')], max_length=255)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='app1.company')),
            ],
        ),
    ]
